import { precacheAndRoute } from 'workbox-precaching';

// Precaching automatically generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST);

let activeChatId = null;
let isAppVisible = false;

self.addEventListener('install', (event) => {
  self.skipWaiting();
  console.log('[Service Worker] Instalado exitosamente con Workbox.');
});

self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activado y listo para recibir Push.');
});

// Escuchar mensajes del cliente (App reactiva)
self.addEventListener('message', (event) => {
  if (event.data) {
    if (event.data.type === 'SET_ACTIVE_CHAT') {
      activeChatId = event.data.id_grupo;
    }
    if (event.data.type === 'SET_APP_VISIBILITY') {
      isAppVisible = event.data.visible;
    }
  }
});

// Manejo de clicks en las notificaciones del SO
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Al hacer clic en la notificación, abre o enfoca la pestaña de AURA
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Si ya hay una pestaña abierta con la app, enfócala
      for (let client of windowClients) {
        if (client.url.includes('/') && 'focus' in client) {
          return client.focus();
        }
      }
      // Si no hay ninguna abierta, abre una nueva
      if (clients.openWindow) {
        return clients.openWindow('/');
      }
    })
  );
});

// Manejo de notificaciones Push en segundo plano
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Notificación Push recibida.');
  let data = { title: 'AURA', body: 'Nueva notificación recibida' };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: 'AURA', body: event.data.text() };
    }
  }

  const options = {
    body: data.body || data.message || '',
    icon: '/icon-192x192.png',
    vibrate: [200, 100, 200],
    data: data.data || {},
    requireInteraction: true
  };

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // 1. Validar por el estado en tiempo real enviado por mensajes del cliente
      const targetGroupId = data.data ? data.data.id_grupo : null;
      const isViewingActiveChat = isAppVisible && activeChatId && targetGroupId && activeChatId === targetGroupId;

      // 2. Validar como respaldo revisando el foco e URL de las ventanas abiertas
      const isUserActiveInChatWindow = windowClients.some((client) => {
        try {
          const url = new URL(client.url);
          const isChatPath = url.pathname.startsWith('/chats');
          return client.focused && isChatPath && (!targetGroupId || activeChatId === targetGroupId);
        } catch (e) {
          return false;
        }
      });

      if (isViewingActiveChat || isUserActiveInChatWindow) {
        console.log('[Service Worker] El usuario está activo en este chat específico, omitiendo notificación push.');
        return;
      }

      return self.registration.showNotification(data.title, options);
    })
  );
});
