import { precacheAndRoute } from 'workbox-precaching';

// Precaching automatically generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST);

let activeChatId = null;
let isAppVisible = false;

const getAppAssetUrl = (assetPath) => {
  const scopeUrl = self.registration?.scope || self.location.origin;
  return new URL(assetPath, scopeUrl).toString();
};

const getNotificationIcon = () => getAppAssetUrl('/logo.png');
const getNotificationBadge = () => getAppAssetUrl('/badge.svg');

self.addEventListener('install', (event) => {
  self.skipWaiting();
  console.log('[SW] Instalado exitosamente con Workbox.');
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
  console.log('[SW] Activado y listo para recibir Push.');
});

// Escuchar mensajes del cliente (App reactiva)
self.addEventListener('message', (event) => {
  if (event.data) {
    if (event.data.type === 'SET_ACTIVE_CHAT') {
      activeChatId = event.data.id_grupo;
    }
    if (event.data.type === 'SET_APP_VISIBILITY') {
      isAppVisible = event.data.visible;
    }
  }
});

// NOTA: Se eliminó el listener 'sync' porque Background Sync
// ya no se registra desde el cliente (evita NotAllowedError).
// Las alertas se entregan únicamente vía Web Push desde la Edge Function.

// Manejo de clicks en las notificaciones del SO
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const targetUrl = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (let client of windowClients) {
        if ('focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow(targetUrl);
      }
    })
  );
});

// ─────────────────────────────────────────────────────────────────────────────
// PUSH HANDLER — notificaciones en segundo plano / app cerrada
//
// Estrategia:
//  • Alertas académicas (type empieza con "academic_"): SIEMPRE se muestran.
//    El servidor las envía desde la Edge Function cuando la app puede estar cerrada.
//  • Mensajes de chat: se suprimen solo si el usuario está activo en ese chat.
// ─────────────────────────────────────────────────────────────────────────────
self.addEventListener('push', (event) => {
  console.log('[SW] ⭐ Push recibido:', event.data ? event.data.text() : '(sin payload)');

  let data = { title: 'AURA', body: 'Nueva notificación' };

  if (event.data) {
    try {
      data = event.data.json();
    } catch {
      data = { title: 'AURA', body: event.data.text() };
    }
  }

  const notifType = data.data?.type || '';
  const isAcademicAlert = notifType.startsWith('academic_');

  console.log('[SW] Tipo:', notifType, '| Es alerta académica:', isAcademicAlert);

  const options = {
    body: data.body || data.message || '',
    icon: getNotificationIcon(),
    badge: getNotificationBadge(),
    vibrate: [200, 100, 200],
    data: data.data || {},
    requireInteraction: true,
    // 'tag' evita duplicados en el SO: una notif del mismo tag reemplaza la anterior
    tag: data.tag || `aura-${notifType || 'general'}`,
  };

  // Alertas académicas: mostrar siempre, sin consultar clientes React
  if (isAcademicAlert) {
    console.log('[SW] Mostrando alerta académica:', data.title);
    event.waitUntil(
      self.registration.showNotification(data.title, options)
    );
    return;
  }

  // Mensajes de chat: suprimir solo si el usuario está en ese chat exacto
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        const targetGroupId = data.data?.id_grupo ?? null;

        if (targetGroupId) {
          const isActiveInTargetChat = windowClients.some((client) => {
            try {
              return (
                client.focused &&
                new URL(client.url).pathname.startsWith('/chats') &&
                activeChatId === targetGroupId
              );
            } catch {
              return false;
            }
          });

          if (isActiveInTargetChat) {
            console.log('[SW] Usuario activo en el chat destino — notificación suprimida.');
            return;
          }
        }

        return self.registration.showNotification(data.title, options);
      })
  );
});
