import { precacheAndRoute } from 'workbox-precaching';

// Precaching automatically generated by Vite PWA
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('install', (event) => {
  self.skipWaiting();
  console.log('[Service Worker] Instalado exitosamente con Workbox.');
});

self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activado y listo para recibir Push.');
});

// Manejo de clicks en las notificaciones del SO
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Al hacer clic en la notificación, abre o enfoca la pestaña de AcademicAI
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Si ya hay una pestaña abierta con la app, enfócala
      for (let client of windowClients) {
        if (client.url.includes('/') && 'focus' in client) {
          return client.focus();
        }
      }
      // Si no hay ninguna abierta, abre una nueva
      if (clients.openWindow) {
        return clients.openWindow('/');
      }
    })
  );
});

// Manejo de notificaciones Push en segundo plano
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Notificación Push recibida.');
  let data = { title: 'AcademicAI', body: 'Nueva notificación recibida' };
  
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { title: 'AcademicAI', body: event.data.text() };
    }
  }

  const options = {
    body: data.body || data.message || '',
    icon: '/favicon.ico',
    vibrate: [200, 100, 200],
    data: data.data || {},
    requireInteraction: true
  };

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Determinar si el usuario está actualmente activo mirando la pantalla de chats
      const isUserActiveInChat = windowClients.some((client) => {
        try {
          const url = new URL(client.url);
          return client.focused && url.pathname.startsWith('/chats');
        } catch (e) {
          return false;
        }
      });

      if (isUserActiveInChat) {
        console.log('[Service Worker] El usuario está activo en el chat, omitiendo notificación.');
        return;
      }

      return self.registration.showNotification(data.title, options);
    })
  );
});
